### ISSUE TITLE
WAIT_TIME

### ISSUE THREAD

**Issue by herenickname** [tvanro/prerender-alpine#12]
Hello, sometimes needs to wait for the page to fully load (for example, long responses from the API server).
Could you add a "WAIT_TIME" env parameter (or something similar) to make the script wait a bit for the site to fully load?

**Comment by tvanro** [comment]
Hi @herenickname ,

Prerender accepts env parameter `PAGE_LOAD_TIME`: https://github.com/prerender/prerender#pageloadtimeout

Maximum number of milliseconds to wait while downloading the page, waiting for all pending requests/ajax calls to complete before timing out and continuing on. Time out condition does not cause an error, it just returns the HTML on the page at that moment.
`Default: 20000`

For example for a page load timeout of 60 seconds:
`docker run -p 3000:3000 -e PAGE_LOAD_TIMEOUT=60000 tvanro/prerender-alpine:6.5.0`
