### ISSUE TITLE
New release date?

### ISSUE THREAD

**Issue by TheMY3** [tvanro/prerender-alpine#13]
Hello, how often do you plan to update dependencies? I saw that prerender 5.20.0 was released already.

**Comment by tvanro** [comment]
Hi @TheMY3 , 

`tvanro/prerender-alpine:6.5.0` is now available with updated dependencies:
- Prerender 5.20.0
- Chromium 99.0.4844.84
- Node 16.15.0

Will make sure to update dependencies a bit more often.
