### ISSUE TITLE
Cannot start chrome with 6.6.0

### ISSUE THREAD

**Issue by boldtrn** [tvanro/prerender-alpine#17]
We just recenlty upgraded to 6.6.0 and chrome won't start, going back to 6.5.0 everything works fine, even if we use the very basic  call without any config:
`docker run -p 3000:3000 tvanro/prerender-alpine:6.6.0`

We believe this might be related to the latest version of Chrome not being able to start anymore.

**Comment by tvanro** [comment]
Thank you for reporting this issue @boldtrn 

Could you share me some more details about your environment and error you're getting with 6.6.0?

**Comment by boldtrn** [comment]
It happened on different machines, I tried for example an Ubuntu LTS machine with x64.

Essentially we are getting: https://github.com/prerender/prerender/issues/775

I works with 6.5.0. It seems to be independent from the prerender version bump. Therefore, I believe the issue is related to something that changed for Chrome. 

I also forked this repo and tried a few different things, like using bookworm instead of alpine and the changes mentioned here: https://github.com/prerender/prerender/pull/779

I had to stop investigating further at some point.

**Comment by tvanro** [comment]
I was able to reproduce the issue on my side by upgrading Docker on my machine to version 26.

Seems the easiest solution for now is to roll back to node:16-alpine base image as was used with 6.5.0. 
I will keep an eye on future fix for this issue so latest Node & Chrome could be used again.

Have a try with 6.6.1:
```
docker pull tvanro/prerender-alpine:6.6.1
docker run -p 3000:3000 tvanro/prerender-alpine:6.6.1
```

**Comment by boldtrn** [comment]
Thanks for looking into this. I can verify that it works with 6.6.1.

**Comment by mikepray** [comment]
I found this issue just recently on M2 MacOSX. Updating Docker daemon (from 4.20.x to 4.30.0) seemed to be what solved it. I also gave my Docker daemon a lot more memory.
